const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const image=(n,color=[100,100,100,255])=>new Uint8ClampedArray(Array.from({length:n},()=>color).flat());
const rect=(changes={})=>({id:'r1',type:'protect',x:0,y:0,w:1,h:1,title:'x',note:'',criteria:'',verified:false,...changes});
test('rectangle clamps reverse dragging',()=>assert.deepEqual(C.rectFromPoints({x:.8,y:.9},{x:.2,y:.1}),{x:.2,y:.1,w:.6000000000000001,h:.8}));
test('rectangle clamps outside coordinates',()=>assert.deepEqual(C.rectFromPoints({x:-1,y:-1},{x:2,y:3}),{x:0,y:0,w:1,h:1}));
test('zero-area rectangle rejected',()=>assert.equal(C.validRect(rect({w:0})),false));
test('NaN coordinate rejected',()=>assert.equal(C.validRect(rect({x:NaN})),false));
test('off-image rectangle rejected',()=>assert.equal(C.validRect(rect({x:.8,w:.4})),false));
test('small input stays same size',()=>assert.deepEqual(C.workSize(600,400),{width:600,height:400,scale:1}));
test('large image scales proportionally',()=>assert.deepEqual(C.workSize(4000,2000),{width:2000,height:1000,scale:.5}));
test('excessive pixel count rejected',()=>assert.throws(()=>C.workSize(5000,5000)));
test('invalid dimension rejected',()=>assert.throws(()=>C.workSize(0,200)));
test('identical pixels produce zero diff',()=>{const a=image(4);const d=C.comparePixels(a,a,2,2,[]);assert.equal(d.changed,0);assert.equal(d.ratio,0);});
test('one changed pixel in a 2x2 image is 25%',()=>{const a=image(4),b=a.slice();b[0]=200;const d=C.comparePixels(a,b,2,2,[rect()],24);assert.equal(d.ratio,.25);assert.equal(d.stats[0].changed,1);});
test('threshold uses strict greater-than',()=>{const a=image(1),b=image(1,[124,100,100,255]);assert.equal(C.comparePixels(a,b,1,1,[],24).changed,0);});
test('threshold 0 detects any difference',()=>assert.equal(C.comparePixels(image(1),image(1,[101,100,100,255]),1,1,[],0).changed,1));
test('threshold 255 ignores all differences',()=>assert.equal(C.comparePixels(image(1,[0,0,0,255]),image(1,[255,255,255,255]),1,1,[],255).changed,0));
test('ignore removes pixels from denominator',()=>{const a=image(4),b=a.slice();b[0]=255;const d=C.comparePixels(a,b,2,2,[rect({type:'ignore',w:.5,h:.5})]);assert.equal(d.total,3);assert.equal(d.ignored,1);assert.equal(d.changed,0);});
test('ignore precedence also applies inside protected regions',()=>{const a=image(4),b=a.slice();b[0]=255;const d=C.comparePixels(a,b,2,2,[rect(),rect({id:'r2',type:'ignore',w:.5,h:.5})]);assert.equal(d.stats[0].total,3);assert.equal(d.stats[0].changed,0);});
test('all ignored returns null ratio, never NaN',()=>{const a=image(4);const d=C.comparePixels(a,a,2,2,[rect({type:'ignore'})]);assert.equal(d.ratio,null);assert.equal(d.total,0);});
test('overlapping ignore regions not double-counted',()=>{const a=image(4);assert.equal(C.comparePixels(a,a,2,2,[rect({type:'ignore'}),rect({id:'b',type:'ignore'})]).ignored,4);});
test('mismatched pixel array lengths rejected',()=>assert.throws(()=>C.comparePixels(image(4),image(3),2,2,[])));
test('invalid threshold rejected',()=>assert.throws(()=>C.comparePixels(image(1),image(1),1,1,[],-1)));
test('heatmap is fully opaque',()=>{const a=image(4),d=C.comparePixels(a,a,2,2,[]);assert.equal(d.heatmap.length,16);for(let i=3;i<16;i+=4)assert.equal(d.heatmap[i],255);});
const data='data:image/png;base64,aGVsbG8=';
const pack=(changes={})=>({app:'koko-naoshite',version:1,title:'Test',before:{data,name:'a.png'},after:null,regions:[rect()],threshold:24,...changes});
test('project restores manual checks as unverified',()=>assert.equal(C.validateProject(pack({regions:[rect({verified:true})]})).regions[0].verified,false));
test('SVG data URL rejected',()=>assert.throws(()=>C.validateProject(pack({before:{data:'data:image/svg+xml;base64,abc=',name:'bad.svg'}}))));
test('remote image URL rejected',()=>assert.throws(()=>C.validateProject(pack({before:{data:'https://example.com/a.png',name:'x'}}))));
test('duplicate region IDs rejected',()=>assert.throws(()=>C.validateProject(pack({regions:[rect(),rect()]}))));
test('regions without before image rejected',()=>assert.throws(()=>C.validateProject(pack({before:null}))));
test('overlarge number of regions rejected',()=>assert.throws(()=>C.validateProject(pack({regions:Array.from({length:61},(_,i)=>rect({id:String(i)}))}))));
test('empty project is valid',()=>assert.equal(C.validateProject(pack({before:null,regions:[]})).regions.length,0));
test('wrong schema rejected',()=>assert.throws(()=>C.validateProject({...pack(),version:2})));
